void led_setup();
void led_demo();
void led_show_time(int time);
void led_blue_loading(int time);
void led_yellow_loading(int time);
void led_purple_loading(int time);
void led_red_loading(int time);
void led_green_loading(int time);
void led_clear_display();
void led_red_blink();
void led_blue_blink();
void led_green_blink();
void led_yellow_blink();
void led_purple_blink();
